travis:
  secure:
    BINSTAR_TOKEN: eYcyx2vREBTEjDIQAxEpduyvW2O91kD+oXRmw9GthICiLfzEI1PCxYPBJDb8whgXzncvF9rqGl7kmkwq14tmDMnVUdLJ1EkPKsGWCOdLmC5RcqKLEx4kxk9vaZeJ/C8HSqsDYbDxwVl6Ttq1g5i2FysIwuz3mdcKnj8IRAkgXyjxWo1HwbFagMJPb8tkJ2zOJjLiyLZl9YkVXX21HFetoFaQo94sYZXZYpH7S3pMXJSuRv2zVMvrMOpLb4m771xdNZndVRiot6UQyRP+JOg7OzbkIMyyjYKXt94TLLG1VNiHNiA8WQ+sVi9WxpwAWQbkS0faLxS08AyIV5tZNmngpSmZnd9hn8Yu9v+5WjZZiP6nv5gWLM6DUuDlO2vFL/PXli558moKMCkhYLI9K5kjsqdm1YK6n9CxBjAPURpBQqoS9Lok8yZ44HVWqcRsNCb3Odx7Wy6JHsY7Ez3aXfSwEsj5Dr5LEpHBo0ZotpeymcNKyy41JnE+3BQMjzJZcMXACMQ/8M6rmFEOS7Z0Qys3LdFgmiSpc9sliYLl37tM3dCNBxYUXjrEHHSIt9+RnunVHcma9tCcYhLAG3sp57oYFOrtZ/Ka4KJCSwCl5tfzT+u0YPgPwIAHe0dRbm7X3mmICUG0SAXaSBYOoEZUwA6xe1QDcWq6A2fERGskW2Web0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
